modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="modslaparticulastarterpack"
version="1.0.0"
displayName="ModsLaParticulaStarterPack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="sombr, MCreator"

[[dependencies.modslaparticulastarterpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




