modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="laparticulastarterpack"
version="1.0.0"
displayName="LaParticulaStarterPack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="sombr, MCreator"

[[dependencies.laparticulastarterpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




